name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          cd /home/ubuntu/apitest
          npm install

      - name: Run API Tests
        run: |
          npm install --save-dev supertest
          cd /home/ubuntu/apitest
          npm test  # Assuming you have Jest or another testing framework set up

      - name: Build and Deploy Static Website
        run: |
          cd /home/ubuntu/apitest
          npm run build  # Assuming you have a build script in your package.json

          # Deploy the static website to a hosting service (e.g., GitHub Pages)
          # Add commands based on your hosting service setup

      - name: Deploy API
        run: |
          cd /home/ubuntu/apitest
          # Add commands to start your API server
          npm start  # Assuming you have a start script in your package.json

          # Deploy the API to a server or serverless platform (e.g., Heroku)
          # Add commands based on your deployment setup
